common:
    input_root: ../data/input/
    img_file: train.csv
    seed: &vars 2020
    drop_fname:
    multi_gpu: True
    kaggle:
        data: True
        notebook: True

model:
    name: resnest50
    n_channels: &channel 3
    n_classes: 1
    pretrained: True
    avgpool:
        name: GeM
        params: {}
    head:
        linear:
            name: Linear
            params:
                in_features: 2048
                out_features: 1
    metric:

data:
    train:
        dataset_type: CustomDataset
        img_type: &img_type tile
        is_train: True
        img_size:
            width: &wsize 512
            height: &hsize 512
        n_channels: *channel
        epochs: 10
        loader:
            shuffle: True
            batch_size: 16
            num_workers: 4
        transforms:
            rotate:
                name: Rotate
                params:
                    p: 0.5
                    limit: 10
            hflip:
                name: HorizontalFlip
                params:
                    p: 0.5
            vflip:
                name: VerticalFlip
                params:
                    p: 0.5
    valid:
        dataset_type: CustomDataset
        img_type: *img_type
        is_train: True
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 16
            num_workers: 4
        transforms:
    test:
        dataset_type: CustomDataset
        img_type: *img_type
        is_train: False
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 16
            num_workers: 4
        transforms:

loss: 
    name: RMSELoss
    params: {}

optimizer:
    name: Adam
    params:
        lr: 0.0001

scheduler:
    name: CosineAnnealingLR
    params:
        eta_min: 0.00001
        T_max: 10