common:
    input_root: ../data/input/
    img_file: train.csv
    seed: 2020
    drop_fname:
    kaggle:
        data: True
        notebook: True

model:
    name: resnet18
    n_channels: &channel 3
    n_classes: 1
    pretrained: True
    avgpool:
        name: GeM
        params: {}
    metric:

data:
    train:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: &wsize 256
            height: &hsize 256
        n_channels: *channel
        epochs: 10
        loader:
            shuffle: True
            batch_size: 16
            num_workers: 4
        transforms:
            rotate:
                name: Rotate
                params:
                    p: 0.5
                    limit: 10
            hflip:
                name: HorizontalFlip
                params:
                    p: 0.5
            vflip:
                name: VerticalFlip
                params:
                    p: 0.5
    valid:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 16
            num_workers: 4
        transforms:
    test:
        dataset_type: CustomDataset
        is_train: False
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 16
            num_workers: 4
        transforms:

loss: 
    name: MSELoss
    params: {}

optimizer:
    name: Adam
    params:
        lr: 0.0001

scheduler:
    name: CosineAnnealingLR
    params:
        eta_min: 0.00001
        T_max: 10
    # name: ReduceLROnPlateau
    # params:
    #     mode: min
    #     factor: 0.5
    #     patience: 2
    #     verbose: True
    #     eps: 0.000001