common:
    input_root: ../data/input/
    img_file: train.csv
    seed: &vars 2020
    drop_fname:
    kaggle:
        data: False
        notebook: False

model:
    name: se_resnext50_32x4d
    n_channels: &channel 3
    n_classes: 4
    pretrained: True
    multi_gpu: True
    avgpool:
        name: GeM
        params: {}
    head:
        # act:
        #     name: ReLU
        #     params: {}
        # batch_norm: 
        #     name: BatchNorm1d
        #     params:
        #         num_features: 512
        # drop:
        #     name: Dropout
        #     params:
        #         p: 0.5
        linear1:
            name: Linear
            params:
                in_features: 2048
                out_features: 4
    metric:

data:
    train:
        dataset_type: CustomDataset
        img_type: &img_type tile
        is_train: True
        img_size:
            width: &wsize 256
            height: &hsize 256
        n_channels: *channel
        epochs: 10
        loader:
            shuffle: True
            batch_size: 64
            num_workers: 4
        transforms:
            rotate:
                name: Rotate
                params:
                    p: 0.5
                    limit: 10
            hflip:
                name: HorizontalFlip
                params:
                    p: 0.5
            vflip:
                name: VerticalFlip
                params:
                    p: 0.5
    valid:
        dataset_type: CustomDataset
        img_type: *img_type
        is_train: True
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 32
            num_workers: 4
        transforms:
    test:
        dataset_type: CustomDataset
        img_type: *img_type
        is_train: False
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 32
            num_workers: 4
        transforms:

loss: 
    name: SmoothCrossEntropyLoss
    params:
        smoothing: 0.1

optimizer:
    name: Adam
    params:
        lr: 0.0001

scheduler:
    name: CosineAnnealingLR
    params:
        eta_min: 0.00001
        T_max: 10
    # name: ReduceLROnPlateau
    # params:
    #     mode: min
    #     factor: 0.5
    #     patience: 2
    #     verbose: True
    #     eps: 0.000001